name: Python Workflow

on:
  push:
    branches:
      - main  # Modify this if your default branch is different

jobs:
  build:
    runs-on: self-hosted  # Use the name of your self-hosted runner group if you have multiple
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you want to use

      - name: Execute Python script
        run: python hello.py
